package com.livinglibrary.mapper;

import com.livinglibrary.po.Forumcomment;
import com.livinglibrary.po.ForumcommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ForumcommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcomment
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	long countByExample(ForumcommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcomment
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	int deleteByExample(ForumcommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcomment
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	int deleteByPrimaryKey(Integer commentid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcomment
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	int insert(Forumcomment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcomment
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	int insertSelective(Forumcomment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcomment
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	List<Forumcomment> selectByExampleWithBLOBs(ForumcommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcomment
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	List<Forumcomment> selectByExample(ForumcommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcomment
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	Forumcomment selectByPrimaryKey(Integer commentid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcomment
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Forumcomment record, @Param("example") ForumcommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcomment
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") Forumcomment record, @Param("example") ForumcommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcomment
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	int updateByExample(@Param("record") Forumcomment record, @Param("example") ForumcommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcomment
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	int updateByPrimaryKeySelective(Forumcomment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcomment
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(Forumcomment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcomment
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	int updateByPrimaryKey(Forumcomment record);
}