package com.livinglibrary.mapper;

import com.livinglibrary.po.Forumcategory;
import com.livinglibrary.po.ForumcategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ForumcategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcategory
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	long countByExample(ForumcategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcategory
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	int deleteByExample(ForumcategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcategory
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	int deleteByPrimaryKey(Integer categoryid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcategory
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	int insert(Forumcategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcategory
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	int insertSelective(Forumcategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcategory
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	List<Forumcategory> selectByExample(ForumcategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcategory
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	Forumcategory selectByPrimaryKey(Integer categoryid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcategory
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Forumcategory record, @Param("example") ForumcategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcategory
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	int updateByExample(@Param("record") Forumcategory record, @Param("example") ForumcategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcategory
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	int updateByPrimaryKeySelective(Forumcategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table forumcategory
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	int updateByPrimaryKey(Forumcategory record);
}