package com.livinglibrary.mapper;

import com.livinglibrary.po.Guesttype;
import com.livinglibrary.po.GuesttypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GuesttypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guesttype
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	long countByExample(GuesttypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guesttype
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int deleteByExample(GuesttypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guesttype
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int deleteByPrimaryKey(Integer typeid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guesttype
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int insert(Guesttype record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guesttype
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int insertSelective(Guesttype record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guesttype
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	List<Guesttype> selectByExample(GuesttypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guesttype
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	Guesttype selectByPrimaryKey(Integer typeid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guesttype
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Guesttype record, @Param("example") GuesttypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guesttype
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByExample(@Param("record") Guesttype record, @Param("example") GuesttypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guesttype
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByPrimaryKeySelective(Guesttype record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guesttype
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByPrimaryKey(Guesttype record);
}