package com.livinglibrary.mapper;

import com.livinglibrary.po.Invitation;
import com.livinglibrary.po.InvitationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InvitationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	long countByExample(InvitationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int deleteByExample(InvitationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int insert(Invitation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int insertSelective(Invitation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	List<Invitation> selectByExample(InvitationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	Invitation selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Invitation record, @Param("example") InvitationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExample(@Param("record") Invitation record, @Param("example") InvitationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKeySelective(Invitation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKey(Invitation record);
}