package com.livinglibrary.mapper;

import com.livinglibrary.po.ModuleInfo;
import com.livinglibrary.po.ModuleInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModuleInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table module_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	long countByExample(ModuleInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table module_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int deleteByExample(ModuleInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table module_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table module_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int insert(ModuleInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table module_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int insertSelective(ModuleInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table module_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	List<ModuleInfo> selectByExample(ModuleInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table module_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	ModuleInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table module_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExampleSelective(@Param("record") ModuleInfo record, @Param("example") ModuleInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table module_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExample(@Param("record") ModuleInfo record, @Param("example") ModuleInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table module_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKeySelective(ModuleInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table module_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKey(ModuleInfo record);
}