package com.livinglibrary.mapper;

import com.livinglibrary.po.NewsInfo;
import com.livinglibrary.po.NewsInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	long countByExample(NewsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int deleteByExample(NewsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int insert(NewsInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int insertSelective(NewsInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	List<NewsInfo> selectByExampleWithBLOBs(NewsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	List<NewsInfo> selectByExample(NewsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	NewsInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExampleSelective(@Param("record") NewsInfo record, @Param("example") NewsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExampleWithBLOBs(@Param("record") NewsInfo record, @Param("example") NewsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExample(@Param("record") NewsInfo record, @Param("example") NewsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKeySelective(NewsInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(NewsInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKey(NewsInfo record);
}