package com.livinglibrary.mapper;

import com.livinglibrary.po.Pastreview;
import com.livinglibrary.po.PastreviewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PastreviewMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pastreview
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	long countByExample(PastreviewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pastreview
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int deleteByExample(PastreviewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pastreview
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int deleteByPrimaryKey(Integer guestid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pastreview
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int insert(Pastreview record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pastreview
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int insertSelective(Pastreview record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pastreview
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	List<Pastreview> selectByExampleWithBLOBs(PastreviewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pastreview
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	List<Pastreview> selectByExample(PastreviewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pastreview
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	Pastreview selectByPrimaryKey(Integer guestid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pastreview
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Pastreview record, @Param("example") PastreviewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pastreview
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByExampleWithBLOBs(@Param("record") Pastreview record, @Param("example") PastreviewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pastreview
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByExample(@Param("record") Pastreview record, @Param("example") PastreviewExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pastreview
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByPrimaryKeySelective(Pastreview record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pastreview
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(Pastreview record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pastreview
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByPrimaryKey(Pastreview record);
}