package com.livinglibrary.mapper;

import com.livinglibrary.po.Registrationrecord;
import com.livinglibrary.po.RegistrationrecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegistrationrecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registrationrecord
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	long countByExample(RegistrationrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registrationrecord
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int deleteByExample(RegistrationrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registrationrecord
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registrationrecord
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int insert(Registrationrecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registrationrecord
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int insertSelective(Registrationrecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registrationrecord
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	List<Registrationrecord> selectByExampleWithBLOBs(RegistrationrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registrationrecord
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	List<Registrationrecord> selectByExample(RegistrationrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registrationrecord
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	Registrationrecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registrationrecord
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Registrationrecord record,
			@Param("example") RegistrationrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registrationrecord
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByExampleWithBLOBs(@Param("record") Registrationrecord record,
			@Param("example") RegistrationrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registrationrecord
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByExample(@Param("record") Registrationrecord record,
			@Param("example") RegistrationrecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registrationrecord
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByPrimaryKeySelective(Registrationrecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registrationrecord
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(Registrationrecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table registrationrecord
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByPrimaryKey(Registrationrecord record);
}