package com.livinglibrary.mapper;

import com.livinglibrary.po.Replies;
import com.livinglibrary.po.RepliesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepliesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table replies
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	long countByExample(RepliesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table replies
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int deleteByExample(RepliesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table replies
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int deleteByPrimaryKey(Integer rid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table replies
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int insert(Replies record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table replies
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int insertSelective(Replies record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table replies
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	List<Replies> selectByExampleWithBLOBs(RepliesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table replies
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	List<Replies> selectByExample(RepliesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table replies
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	Replies selectByPrimaryKey(Integer rid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table replies
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Replies record, @Param("example") RepliesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table replies
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExampleWithBLOBs(@Param("record") Replies record, @Param("example") RepliesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table replies
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExample(@Param("record") Replies record, @Param("example") RepliesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table replies
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKeySelective(Replies record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table replies
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(Replies record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table replies
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKey(Replies record);
}