package com.livinglibrary.mapper;

import com.livinglibrary.po.ReviewInfo;
import com.livinglibrary.po.ReviewInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReviewInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table review_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	long countByExample(ReviewInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table review_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int deleteByExample(ReviewInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table review_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table review_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int insert(ReviewInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table review_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int insertSelective(ReviewInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table review_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	List<ReviewInfo> selectByExampleWithBLOBs(ReviewInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table review_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	List<ReviewInfo> selectByExample(ReviewInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table review_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	ReviewInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table review_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExampleSelective(@Param("record") ReviewInfo record, @Param("example") ReviewInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table review_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExampleWithBLOBs(@Param("record") ReviewInfo record, @Param("example") ReviewInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table review_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExample(@Param("record") ReviewInfo record, @Param("example") ReviewInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table review_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKeySelective(ReviewInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table review_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(ReviewInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table review_info
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKey(ReviewInfo record);
}