package com.livinglibrary.mapper;

import com.livinglibrary.po.RolePermission;
import com.livinglibrary.po.RolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	long countByExample(RolePermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int deleteByExample(RolePermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int deleteByPrimaryKey(Integer roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int insert(RolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int insertSelective(RolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	List<RolePermission> selectByExample(RolePermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	RolePermission selectByPrimaryKey(Integer roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByExampleSelective(@Param("record") RolePermission record,
			@Param("example") RolePermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByExample(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByPrimaryKeySelective(RolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByPrimaryKey(RolePermission record);
}