package com.livinglibrary.mapper;

import com.livinglibrary.po.Userpost;
import com.livinglibrary.po.UserpostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserpostMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	long countByExample(UserpostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int deleteByExample(UserpostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int deleteByPrimaryKey(String tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int insert(Userpost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int insertSelective(Userpost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	List<Userpost> selectByExampleWithBLOBs(UserpostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	List<Userpost> selectByExample(UserpostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	Userpost selectByPrimaryKey(String tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Userpost record, @Param("example") UserpostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExampleWithBLOBs(@Param("record") Userpost record, @Param("example") UserpostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByExample(@Param("record") Userpost record, @Param("example") UserpostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKeySelective(Userpost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(Userpost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	int updateByPrimaryKey(Userpost record);
}