package com.livinglibrary.mapper;

import com.livinglibrary.po.Vedio;
import com.livinglibrary.po.VedioExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VedioMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vedio
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	long countByExample(VedioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vedio
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int deleteByExample(VedioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vedio
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vedio
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int insert(Vedio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vedio
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int insertSelective(Vedio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vedio
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	List<Vedio> selectByExample(VedioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vedio
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	Vedio selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vedio
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Vedio record, @Param("example") VedioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vedio
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByExample(@Param("record") Vedio record, @Param("example") VedioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vedio
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByPrimaryKeySelective(Vedio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vedio
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	int updateByPrimaryKey(Vedio record);
}