package com.livinglibrary.mapper;

import com.livinglibrary.po.Vediotype;
import com.livinglibrary.po.VediotypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VediotypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vediotype
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    long countByExample(VediotypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vediotype
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    int deleteByExample(VediotypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vediotype
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    int deleteByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vediotype
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    int insert(Vediotype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vediotype
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    int insertSelective(Vediotype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vediotype
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    List<Vediotype> selectByExample(VediotypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vediotype
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    Vediotype selectByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vediotype
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") Vediotype record, @Param("example") VediotypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vediotype
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    int updateByExample(@Param("record") Vediotype record, @Param("example") VediotypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vediotype
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    int updateByPrimaryKeySelective(Vediotype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vediotype
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    int updateByPrimaryKey(Vediotype record);
}