package com.livinglibrary.po;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class BoardmessageExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public BoardmessageExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andGuestidIsNull() {
			addCriterion("guestid is null");
			return (Criteria) this;
		}

		public Criteria andGuestidIsNotNull() {
			addCriterion("guestid is not null");
			return (Criteria) this;
		}

		public Criteria andGuestidEqualTo(Integer value) {
			addCriterion("guestid =", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidNotEqualTo(Integer value) {
			addCriterion("guestid <>", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidGreaterThan(Integer value) {
			addCriterion("guestid >", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidGreaterThanOrEqualTo(Integer value) {
			addCriterion("guestid >=", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidLessThan(Integer value) {
			addCriterion("guestid <", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidLessThanOrEqualTo(Integer value) {
			addCriterion("guestid <=", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidIn(List<Integer> values) {
			addCriterion("guestid in", values, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidNotIn(List<Integer> values) {
			addCriterion("guestid not in", values, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidBetween(Integer value1, Integer value2) {
			addCriterion("guestid between", value1, value2, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidNotBetween(Integer value1, Integer value2) {
			addCriterion("guestid not between", value1, value2, "guestid");
			return (Criteria) this;
		}

		public Criteria andStuidIsNull() {
			addCriterion("stuid is null");
			return (Criteria) this;
		}

		public Criteria andStuidIsNotNull() {
			addCriterion("stuid is not null");
			return (Criteria) this;
		}

		public Criteria andStuidEqualTo(String value) {
			addCriterion("stuid =", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidNotEqualTo(String value) {
			addCriterion("stuid <>", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidGreaterThan(String value) {
			addCriterion("stuid >", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidGreaterThanOrEqualTo(String value) {
			addCriterion("stuid >=", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidLessThan(String value) {
			addCriterion("stuid <", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidLessThanOrEqualTo(String value) {
			addCriterion("stuid <=", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidLike(String value) {
			addCriterion("stuid like", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidNotLike(String value) {
			addCriterion("stuid not like", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidIn(List<String> values) {
			addCriterion("stuid in", values, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidNotIn(List<String> values) {
			addCriterion("stuid not in", values, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidBetween(String value1, String value2) {
			addCriterion("stuid between", value1, value2, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidNotBetween(String value1, String value2) {
			addCriterion("stuid not between", value1, value2, "stuid");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("content not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andAnonymousIsNull() {
			addCriterion("anonymous is null");
			return (Criteria) this;
		}

		public Criteria andAnonymousIsNotNull() {
			addCriterion("anonymous is not null");
			return (Criteria) this;
		}

		public Criteria andAnonymousEqualTo(Boolean value) {
			addCriterion("anonymous =", value, "anonymous");
			return (Criteria) this;
		}

		public Criteria andAnonymousNotEqualTo(Boolean value) {
			addCriterion("anonymous <>", value, "anonymous");
			return (Criteria) this;
		}

		public Criteria andAnonymousGreaterThan(Boolean value) {
			addCriterion("anonymous >", value, "anonymous");
			return (Criteria) this;
		}

		public Criteria andAnonymousGreaterThanOrEqualTo(Boolean value) {
			addCriterion("anonymous >=", value, "anonymous");
			return (Criteria) this;
		}

		public Criteria andAnonymousLessThan(Boolean value) {
			addCriterion("anonymous <", value, "anonymous");
			return (Criteria) this;
		}

		public Criteria andAnonymousLessThanOrEqualTo(Boolean value) {
			addCriterion("anonymous <=", value, "anonymous");
			return (Criteria) this;
		}

		public Criteria andAnonymousIn(List<Boolean> values) {
			addCriterion("anonymous in", values, "anonymous");
			return (Criteria) this;
		}

		public Criteria andAnonymousNotIn(List<Boolean> values) {
			addCriterion("anonymous not in", values, "anonymous");
			return (Criteria) this;
		}

		public Criteria andAnonymousBetween(Boolean value1, Boolean value2) {
			addCriterion("anonymous between", value1, value2, "anonymous");
			return (Criteria) this;
		}

		public Criteria andAnonymousNotBetween(Boolean value1, Boolean value2) {
			addCriterion("anonymous not between", value1, value2, "anonymous");
			return (Criteria) this;
		}

		public Criteria andPubtimeIsNull() {
			addCriterion("pubtime is null");
			return (Criteria) this;
		}

		public Criteria andPubtimeIsNotNull() {
			addCriterion("pubtime is not null");
			return (Criteria) this;
		}

		public Criteria andPubtimeEqualTo(Date value) {
			addCriterion("pubtime =", value, "pubtime");
			return (Criteria) this;
		}

		public Criteria andPubtimeNotEqualTo(Date value) {
			addCriterion("pubtime <>", value, "pubtime");
			return (Criteria) this;
		}

		public Criteria andPubtimeGreaterThan(Date value) {
			addCriterion("pubtime >", value, "pubtime");
			return (Criteria) this;
		}

		public Criteria andPubtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("pubtime >=", value, "pubtime");
			return (Criteria) this;
		}

		public Criteria andPubtimeLessThan(Date value) {
			addCriterion("pubtime <", value, "pubtime");
			return (Criteria) this;
		}

		public Criteria andPubtimeLessThanOrEqualTo(Date value) {
			addCriterion("pubtime <=", value, "pubtime");
			return (Criteria) this;
		}

		public Criteria andPubtimeIn(List<Date> values) {
			addCriterion("pubtime in", values, "pubtime");
			return (Criteria) this;
		}

		public Criteria andPubtimeNotIn(List<Date> values) {
			addCriterion("pubtime not in", values, "pubtime");
			return (Criteria) this;
		}

		public Criteria andPubtimeBetween(Date value1, Date value2) {
			addCriterion("pubtime between", value1, value2, "pubtime");
			return (Criteria) this;
		}

		public Criteria andPubtimeNotBetween(Date value1, Date value2) {
			addCriterion("pubtime not between", value1, value2, "pubtime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table boardmessage
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boardmessage
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 11 19:49:21 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}