package com.livinglibrary.po;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

public class Boardmessage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column boardmessage.id
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column boardmessage.guestid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer guestid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column boardmessage.stuid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String stuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column boardmessage.content
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column boardmessage.anonymous
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Boolean anonymous;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column boardmessage.pubtime
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	@JSONField(format = "yyyy-MM-dd HH:mm:ss")
	private Date pubtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column boardmessage.id
	 * @return  the value of boardmessage.id
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column boardmessage.id
	 * @param id  the value for boardmessage.id
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column boardmessage.guestid
	 * @return  the value of boardmessage.guestid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getGuestid() {
		return guestid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column boardmessage.guestid
	 * @param guestid  the value for boardmessage.guestid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setGuestid(Integer guestid) {
		this.guestid = guestid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column boardmessage.stuid
	 * @return  the value of boardmessage.stuid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getStuid() {
		return stuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column boardmessage.stuid
	 * @param stuid  the value for boardmessage.stuid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setStuid(String stuid) {
		this.stuid = stuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column boardmessage.content
	 * @return  the value of boardmessage.content
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column boardmessage.content
	 * @param content  the value for boardmessage.content
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column boardmessage.anonymous
	 * @return  the value of boardmessage.anonymous
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Boolean getAnonymous() {
		return anonymous;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column boardmessage.anonymous
	 * @param anonymous  the value for boardmessage.anonymous
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setAnonymous(Boolean anonymous) {
		this.anonymous = anonymous;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column boardmessage.pubtime
	 * @return  the value of boardmessage.pubtime
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Date getPubtime() {
		return pubtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column boardmessage.pubtime
	 * @param pubtime  the value for boardmessage.pubtime
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setPubtime(Date pubtime) {
		this.pubtime = pubtime;
	}
}