package com.livinglibrary.po;

public class Carousel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column carousel.id
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column carousel.url
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String url;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column carousel.id
	 * @return  the value of carousel.id
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column carousel.id
	 * @param id  the value for carousel.id
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column carousel.url
	 * @return  the value of carousel.url
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column carousel.url
	 * @param url  the value for carousel.url
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setUrl(String url) {
		this.url = url;
	}
}