package com.livinglibrary.po;

import java.util.Date;

public class Forumpost {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumpost.postid
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	private Integer postid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumpost.time
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumpost.author
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	private Integer author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumpost.category
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	private Integer category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumpost.title
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumpost.summary
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	private String summary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumpost.looknum
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	private Integer looknum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumpost.commentnum
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	private Integer commentnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumpost.follownum
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	private Integer follownum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumpost.status
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumpost.content
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumpost.postid
	 * @return  the value of forumpost.postid
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public Integer getPostid() {
		return postid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumpost.postid
	 * @param postid  the value for forumpost.postid
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public void setPostid(Integer postid) {
		this.postid = postid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumpost.time
	 * @return  the value of forumpost.time
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumpost.time
	 * @param time  the value for forumpost.time
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumpost.author
	 * @return  the value of forumpost.author
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public Integer getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumpost.author
	 * @param author  the value for forumpost.author
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public void setAuthor(Integer author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumpost.category
	 * @return  the value of forumpost.category
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public Integer getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumpost.category
	 * @param category  the value for forumpost.category
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public void setCategory(Integer category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumpost.title
	 * @return  the value of forumpost.title
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumpost.title
	 * @param title  the value for forumpost.title
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumpost.summary
	 * @return  the value of forumpost.summary
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public String getSummary() {
		return summary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumpost.summary
	 * @param summary  the value for forumpost.summary
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public void setSummary(String summary) {
		this.summary = summary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumpost.looknum
	 * @return  the value of forumpost.looknum
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public Integer getLooknum() {
		return looknum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumpost.looknum
	 * @param looknum  the value for forumpost.looknum
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public void setLooknum(Integer looknum) {
		this.looknum = looknum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumpost.commentnum
	 * @return  the value of forumpost.commentnum
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public Integer getCommentnum() {
		return commentnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumpost.commentnum
	 * @param commentnum  the value for forumpost.commentnum
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public void setCommentnum(Integer commentnum) {
		this.commentnum = commentnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumpost.follownum
	 * @return  the value of forumpost.follownum
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public Integer getFollownum() {
		return follownum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumpost.follownum
	 * @param follownum  the value for forumpost.follownum
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public void setFollownum(Integer follownum) {
		this.follownum = follownum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumpost.status
	 * @return  the value of forumpost.status
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumpost.status
	 * @param status  the value for forumpost.status
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumpost.content
	 * @return  the value of forumpost.content
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumpost.content
	 * @param content  the value for forumpost.content
	 * @mbg.generated  Thu May 03 08:06:12 CST 2018
	 */
	public void setContent(String content) {
		this.content = content;
	}
}