package com.livinglibrary.po;

public class Forumcategory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumcategory.categoryid
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	private Integer categoryid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumcategory.color
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	private String color;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumcategory.name
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumcategory.path
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column forumcategory.postnum
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	private Integer postnum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumcategory.categoryid
	 * @return  the value of forumcategory.categoryid
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	public Integer getCategoryid() {
		return categoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumcategory.categoryid
	 * @param categoryid  the value for forumcategory.categoryid
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumcategory.color
	 * @return  the value of forumcategory.color
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	public String getColor() {
		return color;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumcategory.color
	 * @param color  the value for forumcategory.color
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	public void setColor(String color) {
		this.color = color;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumcategory.name
	 * @return  the value of forumcategory.name
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumcategory.name
	 * @param name  the value for forumcategory.name
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumcategory.path
	 * @return  the value of forumcategory.path
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumcategory.path
	 * @param path  the value for forumcategory.path
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column forumcategory.postnum
	 * @return  the value of forumcategory.postnum
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	public Integer getPostnum() {
		return postnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column forumcategory.postnum
	 * @param postnum  the value for forumcategory.postnum
	 * @mbg.generated  Thu May 03 08:06:13 CST 2018
	 */
	public void setPostnum(Integer postnum) {
		this.postnum = postnum;
	}
}