package com.livinglibrary.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class GuestExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public GuestExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andGuestidIsNull() {
			addCriterion("GuestId is null");
			return (Criteria) this;
		}

		public Criteria andGuestidIsNotNull() {
			addCriterion("GuestId is not null");
			return (Criteria) this;
		}

		public Criteria andGuestidEqualTo(Integer value) {
			addCriterion("GuestId =", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidNotEqualTo(Integer value) {
			addCriterion("GuestId <>", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidGreaterThan(Integer value) {
			addCriterion("GuestId >", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidGreaterThanOrEqualTo(Integer value) {
			addCriterion("GuestId >=", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidLessThan(Integer value) {
			addCriterion("GuestId <", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidLessThanOrEqualTo(Integer value) {
			addCriterion("GuestId <=", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidIn(List<Integer> values) {
			addCriterion("GuestId in", values, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidNotIn(List<Integer> values) {
			addCriterion("GuestId not in", values, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidBetween(Integer value1, Integer value2) {
			addCriterion("GuestId between", value1, value2, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidNotBetween(Integer value1, Integer value2) {
			addCriterion("GuestId not between", value1, value2, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestnameIsNull() {
			addCriterion("GuestName is null");
			return (Criteria) this;
		}

		public Criteria andGuestnameIsNotNull() {
			addCriterion("GuestName is not null");
			return (Criteria) this;
		}

		public Criteria andGuestnameEqualTo(String value) {
			addCriterion("GuestName =", value, "guestname");
			return (Criteria) this;
		}

		public Criteria andGuestnameNotEqualTo(String value) {
			addCriterion("GuestName <>", value, "guestname");
			return (Criteria) this;
		}

		public Criteria andGuestnameGreaterThan(String value) {
			addCriterion("GuestName >", value, "guestname");
			return (Criteria) this;
		}

		public Criteria andGuestnameGreaterThanOrEqualTo(String value) {
			addCriterion("GuestName >=", value, "guestname");
			return (Criteria) this;
		}

		public Criteria andGuestnameLessThan(String value) {
			addCriterion("GuestName <", value, "guestname");
			return (Criteria) this;
		}

		public Criteria andGuestnameLessThanOrEqualTo(String value) {
			addCriterion("GuestName <=", value, "guestname");
			return (Criteria) this;
		}

		public Criteria andGuestnameLike(String value) {
			addCriterion("GuestName like", value, "guestname");
			return (Criteria) this;
		}

		public Criteria andGuestnameNotLike(String value) {
			addCriterion("GuestName not like", value, "guestname");
			return (Criteria) this;
		}

		public Criteria andGuestnameIn(List<String> values) {
			addCriterion("GuestName in", values, "guestname");
			return (Criteria) this;
		}

		public Criteria andGuestnameNotIn(List<String> values) {
			addCriterion("GuestName not in", values, "guestname");
			return (Criteria) this;
		}

		public Criteria andGuestnameBetween(String value1, String value2) {
			addCriterion("GuestName between", value1, value2, "guestname");
			return (Criteria) this;
		}

		public Criteria andGuestnameNotBetween(String value1, String value2) {
			addCriterion("GuestName not between", value1, value2, "guestname");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("Address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("Address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("Address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("Address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("Address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("Address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("Address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("Address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("Address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("Address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("Address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("Address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("Address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("Address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andGuesttypeIsNull() {
			addCriterion("GuestType is null");
			return (Criteria) this;
		}

		public Criteria andGuesttypeIsNotNull() {
			addCriterion("GuestType is not null");
			return (Criteria) this;
		}

		public Criteria andGuesttypeEqualTo(Integer value) {
			addCriterion("GuestType =", value, "guesttype");
			return (Criteria) this;
		}

		public Criteria andGuesttypeNotEqualTo(Integer value) {
			addCriterion("GuestType <>", value, "guesttype");
			return (Criteria) this;
		}

		public Criteria andGuesttypeGreaterThan(Integer value) {
			addCriterion("GuestType >", value, "guesttype");
			return (Criteria) this;
		}

		public Criteria andGuesttypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("GuestType >=", value, "guesttype");
			return (Criteria) this;
		}

		public Criteria andGuesttypeLessThan(Integer value) {
			addCriterion("GuestType <", value, "guesttype");
			return (Criteria) this;
		}

		public Criteria andGuesttypeLessThanOrEqualTo(Integer value) {
			addCriterion("GuestType <=", value, "guesttype");
			return (Criteria) this;
		}

		public Criteria andGuesttypeIn(List<Integer> values) {
			addCriterion("GuestType in", values, "guesttype");
			return (Criteria) this;
		}

		public Criteria andGuesttypeNotIn(List<Integer> values) {
			addCriterion("GuestType not in", values, "guesttype");
			return (Criteria) this;
		}

		public Criteria andGuesttypeBetween(Integer value1, Integer value2) {
			addCriterion("GuestType between", value1, value2, "guesttype");
			return (Criteria) this;
		}

		public Criteria andGuesttypeNotBetween(Integer value1, Integer value2) {
			addCriterion("GuestType not between", value1, value2, "guesttype");
			return (Criteria) this;
		}

		public Criteria andGuestimgIsNull() {
			addCriterion("GuestImg is null");
			return (Criteria) this;
		}

		public Criteria andGuestimgIsNotNull() {
			addCriterion("GuestImg is not null");
			return (Criteria) this;
		}

		public Criteria andGuestimgEqualTo(String value) {
			addCriterion("GuestImg =", value, "guestimg");
			return (Criteria) this;
		}

		public Criteria andGuestimgNotEqualTo(String value) {
			addCriterion("GuestImg <>", value, "guestimg");
			return (Criteria) this;
		}

		public Criteria andGuestimgGreaterThan(String value) {
			addCriterion("GuestImg >", value, "guestimg");
			return (Criteria) this;
		}

		public Criteria andGuestimgGreaterThanOrEqualTo(String value) {
			addCriterion("GuestImg >=", value, "guestimg");
			return (Criteria) this;
		}

		public Criteria andGuestimgLessThan(String value) {
			addCriterion("GuestImg <", value, "guestimg");
			return (Criteria) this;
		}

		public Criteria andGuestimgLessThanOrEqualTo(String value) {
			addCriterion("GuestImg <=", value, "guestimg");
			return (Criteria) this;
		}

		public Criteria andGuestimgLike(String value) {
			addCriterion("GuestImg like", value, "guestimg");
			return (Criteria) this;
		}

		public Criteria andGuestimgNotLike(String value) {
			addCriterion("GuestImg not like", value, "guestimg");
			return (Criteria) this;
		}

		public Criteria andGuestimgIn(List<String> values) {
			addCriterion("GuestImg in", values, "guestimg");
			return (Criteria) this;
		}

		public Criteria andGuestimgNotIn(List<String> values) {
			addCriterion("GuestImg not in", values, "guestimg");
			return (Criteria) this;
		}

		public Criteria andGuestimgBetween(String value1, String value2) {
			addCriterion("GuestImg between", value1, value2, "guestimg");
			return (Criteria) this;
		}

		public Criteria andGuestimgNotBetween(String value1, String value2) {
			addCriterion("GuestImg not between", value1, value2, "guestimg");
			return (Criteria) this;
		}

		public Criteria andIsshowIsNull() {
			addCriterion("IsShow is null");
			return (Criteria) this;
		}

		public Criteria andIsshowIsNotNull() {
			addCriterion("IsShow is not null");
			return (Criteria) this;
		}

		public Criteria andIsshowEqualTo(String value) {
			addCriterion("IsShow =", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowNotEqualTo(String value) {
			addCriterion("IsShow <>", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowGreaterThan(String value) {
			addCriterion("IsShow >", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowGreaterThanOrEqualTo(String value) {
			addCriterion("IsShow >=", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowLessThan(String value) {
			addCriterion("IsShow <", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowLessThanOrEqualTo(String value) {
			addCriterion("IsShow <=", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowLike(String value) {
			addCriterion("IsShow like", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowNotLike(String value) {
			addCriterion("IsShow not like", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowIn(List<String> values) {
			addCriterion("IsShow in", values, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowNotIn(List<String> values) {
			addCriterion("IsShow not in", values, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowBetween(String value1, String value2) {
			addCriterion("IsShow between", value1, value2, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowNotBetween(String value1, String value2) {
			addCriterion("IsShow not between", value1, value2, "isshow");
			return (Criteria) this;
		}

		public Criteria andBegintimeIsNull() {
			addCriterion("BeginTime is null");
			return (Criteria) this;
		}

		public Criteria andBegintimeIsNotNull() {
			addCriterion("BeginTime is not null");
			return (Criteria) this;
		}

		public Criteria andBegintimeEqualTo(Date value) {
			addCriterion("BeginTime =", value, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeNotEqualTo(Date value) {
			addCriterion("BeginTime <>", value, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeGreaterThan(Date value) {
			addCriterion("BeginTime >", value, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeGreaterThanOrEqualTo(Date value) {
			addCriterion("BeginTime >=", value, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeLessThan(Date value) {
			addCriterion("BeginTime <", value, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeLessThanOrEqualTo(Date value) {
			addCriterion("BeginTime <=", value, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeIn(List<Date> values) {
			addCriterion("BeginTime in", values, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeNotIn(List<Date> values) {
			addCriterion("BeginTime not in", values, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeBetween(Date value1, Date value2) {
			addCriterion("BeginTime between", value1, value2, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeNotBetween(Date value1, Date value2) {
			addCriterion("BeginTime not between", value1, value2, "begintime");
			return (Criteria) this;
		}

		public Criteria andEndtimeIsNull() {
			addCriterion("EndTime is null");
			return (Criteria) this;
		}

		public Criteria andEndtimeIsNotNull() {
			addCriterion("EndTime is not null");
			return (Criteria) this;
		}

		public Criteria andEndtimeEqualTo(Date value) {
			addCriterion("EndTime =", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeNotEqualTo(Date value) {
			addCriterion("EndTime <>", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeGreaterThan(Date value) {
			addCriterion("EndTime >", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("EndTime >=", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeLessThan(Date value) {
			addCriterion("EndTime <", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeLessThanOrEqualTo(Date value) {
			addCriterion("EndTime <=", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeIn(List<Date> values) {
			addCriterion("EndTime in", values, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeNotIn(List<Date> values) {
			addCriterion("EndTime not in", values, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeBetween(Date value1, Date value2) {
			addCriterion("EndTime between", value1, value2, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeNotBetween(Date value1, Date value2) {
			addCriterion("EndTime not between", value1, value2, "endtime");
			return (Criteria) this;
		}

		public Criteria andOrdernumIsNull() {
			addCriterion("ordernum is null");
			return (Criteria) this;
		}

		public Criteria andOrdernumIsNotNull() {
			addCriterion("ordernum is not null");
			return (Criteria) this;
		}

		public Criteria andOrdernumEqualTo(Integer value) {
			addCriterion("ordernum =", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumNotEqualTo(Integer value) {
			addCriterion("ordernum <>", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumGreaterThan(Integer value) {
			addCriterion("ordernum >", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumGreaterThanOrEqualTo(Integer value) {
			addCriterion("ordernum >=", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumLessThan(Integer value) {
			addCriterion("ordernum <", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumLessThanOrEqualTo(Integer value) {
			addCriterion("ordernum <=", value, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumIn(List<Integer> values) {
			addCriterion("ordernum in", values, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumNotIn(List<Integer> values) {
			addCriterion("ordernum not in", values, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumBetween(Integer value1, Integer value2) {
			addCriterion("ordernum between", value1, value2, "ordernum");
			return (Criteria) this;
		}

		public Criteria andOrdernumNotBetween(Integer value1, Integer value2) {
			addCriterion("ordernum not between", value1, value2, "ordernum");
			return (Criteria) this;
		}

		public Criteria andAllnumIsNull() {
			addCriterion("allnum is null");
			return (Criteria) this;
		}

		public Criteria andAllnumIsNotNull() {
			addCriterion("allnum is not null");
			return (Criteria) this;
		}

		public Criteria andAllnumEqualTo(Integer value) {
			addCriterion("allnum =", value, "allnum");
			return (Criteria) this;
		}

		public Criteria andAllnumNotEqualTo(Integer value) {
			addCriterion("allnum <>", value, "allnum");
			return (Criteria) this;
		}

		public Criteria andAllnumGreaterThan(Integer value) {
			addCriterion("allnum >", value, "allnum");
			return (Criteria) this;
		}

		public Criteria andAllnumGreaterThanOrEqualTo(Integer value) {
			addCriterion("allnum >=", value, "allnum");
			return (Criteria) this;
		}

		public Criteria andAllnumLessThan(Integer value) {
			addCriterion("allnum <", value, "allnum");
			return (Criteria) this;
		}

		public Criteria andAllnumLessThanOrEqualTo(Integer value) {
			addCriterion("allnum <=", value, "allnum");
			return (Criteria) this;
		}

		public Criteria andAllnumIn(List<Integer> values) {
			addCriterion("allnum in", values, "allnum");
			return (Criteria) this;
		}

		public Criteria andAllnumNotIn(List<Integer> values) {
			addCriterion("allnum not in", values, "allnum");
			return (Criteria) this;
		}

		public Criteria andAllnumBetween(Integer value1, Integer value2) {
			addCriterion("allnum between", value1, value2, "allnum");
			return (Criteria) this;
		}

		public Criteria andAllnumNotBetween(Integer value1, Integer value2) {
			addCriterion("allnum not between", value1, value2, "allnum");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table guest
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guest
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 09 13:47:47 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}