package com.livinglibrary.po;

public class Guesttype {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guesttype.typeId
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer typeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guesttype.typeName
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String typename;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guesttype.typeId
	 * @return  the value of guesttype.typeId
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getTypeid() {
		return typeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guesttype.typeId
	 * @param typeid  the value for guesttype.typeId
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setTypeid(Integer typeid) {
		this.typeid = typeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guesttype.typeName
	 * @return  the value of guesttype.typeName
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getTypename() {
		return typename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guesttype.typeName
	 * @param typename  the value for guesttype.typeName
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setTypename(String typename) {
		this.typename = typename;
	}
}