package com.livinglibrary.po;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class GuestcommentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public GuestcommentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andStuidIsNull() {
			addCriterion("stuid is null");
			return (Criteria) this;
		}

		public Criteria andStuidIsNotNull() {
			addCriterion("stuid is not null");
			return (Criteria) this;
		}

		public Criteria andStuidEqualTo(String value) {
			addCriterion("stuid =", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidNotEqualTo(String value) {
			addCriterion("stuid <>", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidGreaterThan(String value) {
			addCriterion("stuid >", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidGreaterThanOrEqualTo(String value) {
			addCriterion("stuid >=", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidLessThan(String value) {
			addCriterion("stuid <", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidLessThanOrEqualTo(String value) {
			addCriterion("stuid <=", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidLike(String value) {
			addCriterion("stuid like", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidNotLike(String value) {
			addCriterion("stuid not like", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidIn(List<String> values) {
			addCriterion("stuid in", values, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidNotIn(List<String> values) {
			addCriterion("stuid not in", values, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidBetween(String value1, String value2) {
			addCriterion("stuid between", value1, value2, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidNotBetween(String value1, String value2) {
			addCriterion("stuid not between", value1, value2, "stuid");
			return (Criteria) this;
		}

		public Criteria andGuestidIsNull() {
			addCriterion("guestid is null");
			return (Criteria) this;
		}

		public Criteria andGuestidIsNotNull() {
			addCriterion("guestid is not null");
			return (Criteria) this;
		}

		public Criteria andGuestidEqualTo(Integer value) {
			addCriterion("guestid =", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidNotEqualTo(Integer value) {
			addCriterion("guestid <>", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidGreaterThan(Integer value) {
			addCriterion("guestid >", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidGreaterThanOrEqualTo(Integer value) {
			addCriterion("guestid >=", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidLessThan(Integer value) {
			addCriterion("guestid <", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidLessThanOrEqualTo(Integer value) {
			addCriterion("guestid <=", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidIn(List<Integer> values) {
			addCriterion("guestid in", values, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidNotIn(List<Integer> values) {
			addCriterion("guestid not in", values, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidBetween(Integer value1, Integer value2) {
			addCriterion("guestid between", value1, value2, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidNotBetween(Integer value1, Integer value2) {
			addCriterion("guestid not between", value1, value2, "guestid");
			return (Criteria) this;
		}

		public Criteria andIsreplyIsNull() {
			addCriterion("isreply is null");
			return (Criteria) this;
		}

		public Criteria andIsreplyIsNotNull() {
			addCriterion("isreply is not null");
			return (Criteria) this;
		}

		public Criteria andIsreplyEqualTo(Integer value) {
			addCriterion("isreply =", value, "isreply");
			return (Criteria) this;
		}

		public Criteria andIsreplyNotEqualTo(Integer value) {
			addCriterion("isreply <>", value, "isreply");
			return (Criteria) this;
		}

		public Criteria andIsreplyGreaterThan(Integer value) {
			addCriterion("isreply >", value, "isreply");
			return (Criteria) this;
		}

		public Criteria andIsreplyGreaterThanOrEqualTo(Integer value) {
			addCriterion("isreply >=", value, "isreply");
			return (Criteria) this;
		}

		public Criteria andIsreplyLessThan(Integer value) {
			addCriterion("isreply <", value, "isreply");
			return (Criteria) this;
		}

		public Criteria andIsreplyLessThanOrEqualTo(Integer value) {
			addCriterion("isreply <=", value, "isreply");
			return (Criteria) this;
		}

		public Criteria andIsreplyIn(List<Integer> values) {
			addCriterion("isreply in", values, "isreply");
			return (Criteria) this;
		}

		public Criteria andIsreplyNotIn(List<Integer> values) {
			addCriterion("isreply not in", values, "isreply");
			return (Criteria) this;
		}

		public Criteria andIsreplyBetween(Integer value1, Integer value2) {
			addCriterion("isreply between", value1, value2, "isreply");
			return (Criteria) this;
		}

		public Criteria andIsreplyNotBetween(Integer value1, Integer value2) {
			addCriterion("isreply not between", value1, value2, "isreply");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNull() {
			addCriterion("keyword is null");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNotNull() {
			addCriterion("keyword is not null");
			return (Criteria) this;
		}

		public Criteria andKeywordEqualTo(String value) {
			addCriterion("keyword =", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotEqualTo(String value) {
			addCriterion("keyword <>", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThan(String value) {
			addCriterion("keyword >", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThanOrEqualTo(String value) {
			addCriterion("keyword >=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThan(String value) {
			addCriterion("keyword <", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThanOrEqualTo(String value) {
			addCriterion("keyword <=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLike(String value) {
			addCriterion("keyword like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotLike(String value) {
			addCriterion("keyword not like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordIn(List<String> values) {
			addCriterion("keyword in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotIn(List<String> values) {
			addCriterion("keyword not in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordBetween(String value1, String value2) {
			addCriterion("keyword between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotBetween(String value1, String value2) {
			addCriterion("keyword not between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andAirecommendIsNull() {
			addCriterion("AIRecommend is null");
			return (Criteria) this;
		}

		public Criteria andAirecommendIsNotNull() {
			addCriterion("AIRecommend is not null");
			return (Criteria) this;
		}

		public Criteria andAirecommendEqualTo(Integer value) {
			addCriterion("AIRecommend =", value, "airecommend");
			return (Criteria) this;
		}

		public Criteria andAirecommendNotEqualTo(Integer value) {
			addCriterion("AIRecommend <>", value, "airecommend");
			return (Criteria) this;
		}

		public Criteria andAirecommendGreaterThan(Integer value) {
			addCriterion("AIRecommend >", value, "airecommend");
			return (Criteria) this;
		}

		public Criteria andAirecommendGreaterThanOrEqualTo(Integer value) {
			addCriterion("AIRecommend >=", value, "airecommend");
			return (Criteria) this;
		}

		public Criteria andAirecommendLessThan(Integer value) {
			addCriterion("AIRecommend <", value, "airecommend");
			return (Criteria) this;
		}

		public Criteria andAirecommendLessThanOrEqualTo(Integer value) {
			addCriterion("AIRecommend <=", value, "airecommend");
			return (Criteria) this;
		}

		public Criteria andAirecommendIn(List<Integer> values) {
			addCriterion("AIRecommend in", values, "airecommend");
			return (Criteria) this;
		}

		public Criteria andAirecommendNotIn(List<Integer> values) {
			addCriterion("AIRecommend not in", values, "airecommend");
			return (Criteria) this;
		}

		public Criteria andAirecommendBetween(Integer value1, Integer value2) {
			addCriterion("AIRecommend between", value1, value2, "airecommend");
			return (Criteria) this;
		}

		public Criteria andAirecommendNotBetween(Integer value1, Integer value2) {
			addCriterion("AIRecommend not between", value1, value2, "airecommend");
			return (Criteria) this;
		}

		public Criteria andIsshowIsNull() {
			addCriterion("isShow is null");
			return (Criteria) this;
		}

		public Criteria andIsshowIsNotNull() {
			addCriterion("isShow is not null");
			return (Criteria) this;
		}

		public Criteria andIsshowEqualTo(Integer value) {
			addCriterion("isShow =", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowNotEqualTo(Integer value) {
			addCriterion("isShow <>", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowGreaterThan(Integer value) {
			addCriterion("isShow >", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowGreaterThanOrEqualTo(Integer value) {
			addCriterion("isShow >=", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowLessThan(Integer value) {
			addCriterion("isShow <", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowLessThanOrEqualTo(Integer value) {
			addCriterion("isShow <=", value, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowIn(List<Integer> values) {
			addCriterion("isShow in", values, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowNotIn(List<Integer> values) {
			addCriterion("isShow not in", values, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowBetween(Integer value1, Integer value2) {
			addCriterion("isShow between", value1, value2, "isshow");
			return (Criteria) this;
		}

		public Criteria andIsshowNotBetween(Integer value1, Integer value2) {
			addCriterion("isShow not between", value1, value2, "isshow");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNull() {
			addCriterion("addtime is null");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNotNull() {
			addCriterion("addtime is not null");
			return (Criteria) this;
		}

		public Criteria andAddtimeEqualTo(Date value) {
			addCriterion("addtime =", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotEqualTo(Date value) {
			addCriterion("addtime <>", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThan(Date value) {
			addCriterion("addtime >", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("addtime >=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThan(Date value) {
			addCriterion("addtime <", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThanOrEqualTo(Date value) {
			addCriterion("addtime <=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeIn(List<Date> values) {
			addCriterion("addtime in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotIn(List<Date> values) {
			addCriterion("addtime not in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeBetween(Date value1, Date value2) {
			addCriterion("addtime between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotBetween(Date value1, Date value2) {
			addCriterion("addtime not between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andGnameIsNull() {
			addCriterion("gname is null");
			return (Criteria) this;
		}

		public Criteria andGnameIsNotNull() {
			addCriterion("gname is not null");
			return (Criteria) this;
		}

		public Criteria andGnameEqualTo(String value) {
			addCriterion("gname =", value, "gname");
			return (Criteria) this;
		}

		public Criteria andGnameNotEqualTo(String value) {
			addCriterion("gname <>", value, "gname");
			return (Criteria) this;
		}

		public Criteria andGnameGreaterThan(String value) {
			addCriterion("gname >", value, "gname");
			return (Criteria) this;
		}

		public Criteria andGnameGreaterThanOrEqualTo(String value) {
			addCriterion("gname >=", value, "gname");
			return (Criteria) this;
		}

		public Criteria andGnameLessThan(String value) {
			addCriterion("gname <", value, "gname");
			return (Criteria) this;
		}

		public Criteria andGnameLessThanOrEqualTo(String value) {
			addCriterion("gname <=", value, "gname");
			return (Criteria) this;
		}

		public Criteria andGnameLike(String value) {
			addCriterion("gname like", value, "gname");
			return (Criteria) this;
		}

		public Criteria andGnameNotLike(String value) {
			addCriterion("gname not like", value, "gname");
			return (Criteria) this;
		}

		public Criteria andGnameIn(List<String> values) {
			addCriterion("gname in", values, "gname");
			return (Criteria) this;
		}

		public Criteria andGnameNotIn(List<String> values) {
			addCriterion("gname not in", values, "gname");
			return (Criteria) this;
		}

		public Criteria andGnameBetween(String value1, String value2) {
			addCriterion("gname between", value1, value2, "gname");
			return (Criteria) this;
		}

		public Criteria andGnameNotBetween(String value1, String value2) {
			addCriterion("gname not between", value1, value2, "gname");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table guestcomment
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guestcomment
     *
     * @mbg.generated do_not_delete_during_merge Sat Jan 12 12:00:10 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}