package com.livinglibrary.po;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

public class Guestcomment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guestcomment.id
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guestcomment.stuid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String stuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guestcomment.guestid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer guestid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guestcomment.isreply
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer isreply;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guestcomment.keyword
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String keyword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guestcomment.AIRecommend
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer airecommend;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guestcomment.isShow
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer isshow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guestcomment.addtime
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	@JSONField(format = "yyyy-MM-dd HH:mm:ss")
	private Date addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guestcomment.name
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guestcomment.gname
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String gname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column guestcomment.content
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guestcomment.id
	 * @return  the value of guestcomment.id
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guestcomment.id
	 * @param id  the value for guestcomment.id
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guestcomment.stuid
	 * @return  the value of guestcomment.stuid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getStuid() {
		return stuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guestcomment.stuid
	 * @param stuid  the value for guestcomment.stuid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setStuid(String stuid) {
		this.stuid = stuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guestcomment.guestid
	 * @return  the value of guestcomment.guestid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getGuestid() {
		return guestid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guestcomment.guestid
	 * @param guestid  the value for guestcomment.guestid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setGuestid(Integer guestid) {
		this.guestid = guestid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guestcomment.isreply
	 * @return  the value of guestcomment.isreply
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getIsreply() {
		return isreply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guestcomment.isreply
	 * @param isreply  the value for guestcomment.isreply
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setIsreply(Integer isreply) {
		this.isreply = isreply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guestcomment.keyword
	 * @return  the value of guestcomment.keyword
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getKeyword() {
		return keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guestcomment.keyword
	 * @param keyword  the value for guestcomment.keyword
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guestcomment.AIRecommend
	 * @return  the value of guestcomment.AIRecommend
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getAirecommend() {
		return airecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guestcomment.AIRecommend
	 * @param airecommend  the value for guestcomment.AIRecommend
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setAirecommend(Integer airecommend) {
		this.airecommend = airecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guestcomment.isShow
	 * @return  the value of guestcomment.isShow
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getIsshow() {
		return isshow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guestcomment.isShow
	 * @param isshow  the value for guestcomment.isShow
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setIsshow(Integer isshow) {
		this.isshow = isshow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guestcomment.addtime
	 * @return  the value of guestcomment.addtime
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guestcomment.addtime
	 * @param addtime  the value for guestcomment.addtime
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guestcomment.name
	 * @return  the value of guestcomment.name
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guestcomment.name
	 * @param name  the value for guestcomment.name
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guestcomment.gname
	 * @return  the value of guestcomment.gname
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getGname() {
		return gname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guestcomment.gname
	 * @param gname  the value for guestcomment.gname
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setGname(String gname) {
		this.gname = gname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column guestcomment.content
	 * @return  the value of guestcomment.content
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column guestcomment.content
	 * @param content  the value for guestcomment.content
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setContent(String content) {
		this.content = content;
	}
}