package com.livinglibrary.po;

import java.util.Date;

public class Invitation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invitation.id
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invitation.theme
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private String theme;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invitation.GuestId
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private Integer guestid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invitation.BeginTime
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private Date begintime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invitation.EndTime
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private Date endtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invitation.id
	 * @return  the value of invitation.id
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invitation.id
	 * @param id  the value for invitation.id
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invitation.theme
	 * @return  the value of invitation.theme
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public String getTheme() {
		return theme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invitation.theme
	 * @param theme  the value for invitation.theme
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setTheme(String theme) {
		this.theme = theme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invitation.GuestId
	 * @return  the value of invitation.GuestId
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Integer getGuestid() {
		return guestid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invitation.GuestId
	 * @param guestid  the value for invitation.GuestId
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setGuestid(Integer guestid) {
		this.guestid = guestid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invitation.BeginTime
	 * @return  the value of invitation.BeginTime
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Date getBegintime() {
		return begintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invitation.BeginTime
	 * @param begintime  the value for invitation.BeginTime
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setBegintime(Date begintime) {
		this.begintime = begintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invitation.EndTime
	 * @return  the value of invitation.EndTime
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Date getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invitation.EndTime
	 * @param endtime  the value for invitation.EndTime
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}
}