package com.livinglibrary.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InvitationExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public InvitationExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andThemeIsNull() {
			addCriterion("theme is null");
			return (Criteria) this;
		}

		public Criteria andThemeIsNotNull() {
			addCriterion("theme is not null");
			return (Criteria) this;
		}

		public Criteria andThemeEqualTo(String value) {
			addCriterion("theme =", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeNotEqualTo(String value) {
			addCriterion("theme <>", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeGreaterThan(String value) {
			addCriterion("theme >", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeGreaterThanOrEqualTo(String value) {
			addCriterion("theme >=", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeLessThan(String value) {
			addCriterion("theme <", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeLessThanOrEqualTo(String value) {
			addCriterion("theme <=", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeLike(String value) {
			addCriterion("theme like", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeNotLike(String value) {
			addCriterion("theme not like", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeIn(List<String> values) {
			addCriterion("theme in", values, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeNotIn(List<String> values) {
			addCriterion("theme not in", values, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeBetween(String value1, String value2) {
			addCriterion("theme between", value1, value2, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeNotBetween(String value1, String value2) {
			addCriterion("theme not between", value1, value2, "theme");
			return (Criteria) this;
		}

		public Criteria andGuestidIsNull() {
			addCriterion("GuestId is null");
			return (Criteria) this;
		}

		public Criteria andGuestidIsNotNull() {
			addCriterion("GuestId is not null");
			return (Criteria) this;
		}

		public Criteria andGuestidEqualTo(Integer value) {
			addCriterion("GuestId =", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidNotEqualTo(Integer value) {
			addCriterion("GuestId <>", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidGreaterThan(Integer value) {
			addCriterion("GuestId >", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidGreaterThanOrEqualTo(Integer value) {
			addCriterion("GuestId >=", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidLessThan(Integer value) {
			addCriterion("GuestId <", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidLessThanOrEqualTo(Integer value) {
			addCriterion("GuestId <=", value, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidIn(List<Integer> values) {
			addCriterion("GuestId in", values, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidNotIn(List<Integer> values) {
			addCriterion("GuestId not in", values, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidBetween(Integer value1, Integer value2) {
			addCriterion("GuestId between", value1, value2, "guestid");
			return (Criteria) this;
		}

		public Criteria andGuestidNotBetween(Integer value1, Integer value2) {
			addCriterion("GuestId not between", value1, value2, "guestid");
			return (Criteria) this;
		}

		public Criteria andBegintimeIsNull() {
			addCriterion("BeginTime is null");
			return (Criteria) this;
		}

		public Criteria andBegintimeIsNotNull() {
			addCriterion("BeginTime is not null");
			return (Criteria) this;
		}

		public Criteria andBegintimeEqualTo(Date value) {
			addCriterion("BeginTime =", value, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeNotEqualTo(Date value) {
			addCriterion("BeginTime <>", value, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeGreaterThan(Date value) {
			addCriterion("BeginTime >", value, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeGreaterThanOrEqualTo(Date value) {
			addCriterion("BeginTime >=", value, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeLessThan(Date value) {
			addCriterion("BeginTime <", value, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeLessThanOrEqualTo(Date value) {
			addCriterion("BeginTime <=", value, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeIn(List<Date> values) {
			addCriterion("BeginTime in", values, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeNotIn(List<Date> values) {
			addCriterion("BeginTime not in", values, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeBetween(Date value1, Date value2) {
			addCriterion("BeginTime between", value1, value2, "begintime");
			return (Criteria) this;
		}

		public Criteria andBegintimeNotBetween(Date value1, Date value2) {
			addCriterion("BeginTime not between", value1, value2, "begintime");
			return (Criteria) this;
		}

		public Criteria andEndtimeIsNull() {
			addCriterion("EndTime is null");
			return (Criteria) this;
		}

		public Criteria andEndtimeIsNotNull() {
			addCriterion("EndTime is not null");
			return (Criteria) this;
		}

		public Criteria andEndtimeEqualTo(Date value) {
			addCriterion("EndTime =", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeNotEqualTo(Date value) {
			addCriterion("EndTime <>", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeGreaterThan(Date value) {
			addCriterion("EndTime >", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("EndTime >=", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeLessThan(Date value) {
			addCriterion("EndTime <", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeLessThanOrEqualTo(Date value) {
			addCriterion("EndTime <=", value, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeIn(List<Date> values) {
			addCriterion("EndTime in", values, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeNotIn(List<Date> values) {
			addCriterion("EndTime not in", values, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeBetween(Date value1, Date value2) {
			addCriterion("EndTime between", value1, value2, "endtime");
			return (Criteria) this;
		}

		public Criteria andEndtimeNotBetween(Date value1, Date value2) {
			addCriterion("EndTime not between", value1, value2, "endtime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table invitation
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table invitation
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 09 13:47:47 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}