package com.livinglibrary.po;

import java.util.Date;

public class NewsInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_info.id
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_info.module_id
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private Integer moduleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_info.title
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_info.times
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private Integer times;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_info.add_user
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private String addUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_info.add_time
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_info.cont
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private String cont;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_info.id
	 * @return  the value of news_info.id
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_info.id
	 * @param id  the value for news_info.id
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_info.module_id
	 * @return  the value of news_info.module_id
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Integer getModuleId() {
		return moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_info.module_id
	 * @param moduleId  the value for news_info.module_id
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_info.title
	 * @return  the value of news_info.title
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_info.title
	 * @param title  the value for news_info.title
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_info.times
	 * @return  the value of news_info.times
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Integer getTimes() {
		return times;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_info.times
	 * @param times  the value for news_info.times
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setTimes(Integer times) {
		this.times = times;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_info.add_user
	 * @return  the value of news_info.add_user
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public String getAddUser() {
		return addUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_info.add_user
	 * @param addUser  the value for news_info.add_user
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setAddUser(String addUser) {
		this.addUser = addUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_info.add_time
	 * @return  the value of news_info.add_time
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_info.add_time
	 * @param addTime  the value for news_info.add_time
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_info.cont
	 * @return  the value of news_info.cont
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public String getCont() {
		return cont;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_info.cont
	 * @param cont  the value for news_info.cont
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setCont(String cont) {
		this.cont = cont;
	}
}