package com.livinglibrary.po;

import java.util.Date;

public class Pastreview {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pastreview.guestid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer guestid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pastreview.time
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pastreview.editor
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String editor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pastreview.content
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pastreview.guestid
	 * @return  the value of pastreview.guestid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getGuestid() {
		return guestid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pastreview.guestid
	 * @param guestid  the value for pastreview.guestid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setGuestid(Integer guestid) {
		this.guestid = guestid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pastreview.time
	 * @return  the value of pastreview.time
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pastreview.time
	 * @param time  the value for pastreview.time
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pastreview.editor
	 * @return  the value of pastreview.editor
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getEditor() {
		return editor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pastreview.editor
	 * @param editor  the value for pastreview.editor
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setEditor(String editor) {
		this.editor = editor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pastreview.content
	 * @return  the value of pastreview.content
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pastreview.content
	 * @param content  the value for pastreview.content
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setContent(String content) {
		this.content = content;
	}
}