package com.livinglibrary.po;

public class Permission {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.id
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.available
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	private Integer available;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.name
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.permission
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	private String permission;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.url
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	private String url;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.id
	 * @return  the value of permission.id
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.id
	 * @param id  the value for permission.id
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.available
	 * @return  the value of permission.available
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	public Integer getAvailable() {
		return available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.available
	 * @param available  the value for permission.available
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	public void setAvailable(Integer available) {
		this.available = available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.name
	 * @return  the value of permission.name
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.name
	 * @param name  the value for permission.name
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.permission
	 * @return  the value of permission.permission
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	public String getPermission() {
		return permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.permission
	 * @param permission  the value for permission.permission
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	public void setPermission(String permission) {
		this.permission = permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.url
	 * @return  the value of permission.url
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.url
	 * @param url  the value for permission.url
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	public void setUrl(String url) {
		this.url = url;
	}
}