package com.livinglibrary.po;

import java.util.Date;

public class Replies {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column replies.rid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private Integer rid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column replies.tid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private String tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column replies.stuid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private String stuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column replies.postid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private Integer postid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column replies.time
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column replies.replytext
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private String replytext;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column replies.rid
	 * @return  the value of replies.rid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Integer getRid() {
		return rid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column replies.rid
	 * @param rid  the value for replies.rid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setRid(Integer rid) {
		this.rid = rid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column replies.tid
	 * @return  the value of replies.tid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public String getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column replies.tid
	 * @param tid  the value for replies.tid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setTid(String tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column replies.stuid
	 * @return  the value of replies.stuid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public String getStuid() {
		return stuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column replies.stuid
	 * @param stuid  the value for replies.stuid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setStuid(String stuid) {
		this.stuid = stuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column replies.postid
	 * @return  the value of replies.postid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Integer getPostid() {
		return postid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column replies.postid
	 * @param postid  the value for replies.postid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setPostid(Integer postid) {
		this.postid = postid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column replies.time
	 * @return  the value of replies.time
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column replies.time
	 * @param time  the value for replies.time
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column replies.replytext
	 * @return  the value of replies.replytext
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public String getReplytext() {
		return replytext;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column replies.replytext
	 * @param replytext  the value for replies.replytext
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setReplytext(String replytext) {
		this.replytext = replytext;
	}
}