package com.livinglibrary.po;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.id
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.description
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.role
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.available
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer available;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.id
	 * @return  the value of role.id
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.id
	 * @param id  the value for role.id
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.description
	 * @return  the value of role.description
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.description
	 * @param description  the value for role.description
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.role
	 * @return  the value of role.role
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.role
	 * @param role  the value for role.role
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setRole(String role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.available
	 * @return  the value of role.available
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getAvailable() {
		return available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.available
	 * @param available  the value for role.available
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setAvailable(Integer available) {
		this.available = available;
	}
}