package com.livinglibrary.po;

public class Systemset {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column systemset.liveaddress
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String liveaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column systemset.serveraddress
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String serveraddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column systemset.imgaddress
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String imgaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column systemset.vedioaddress
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String vedioaddress;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column systemset.liveaddress
	 * @return  the value of systemset.liveaddress
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getLiveaddress() {
		return liveaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column systemset.liveaddress
	 * @param liveaddress  the value for systemset.liveaddress
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setLiveaddress(String liveaddress) {
		this.liveaddress = liveaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column systemset.serveraddress
	 * @return  the value of systemset.serveraddress
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getServeraddress() {
		return serveraddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column systemset.serveraddress
	 * @param serveraddress  the value for systemset.serveraddress
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setServeraddress(String serveraddress) {
		this.serveraddress = serveraddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column systemset.imgaddress
	 * @return  the value of systemset.imgaddress
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getImgaddress() {
		return imgaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column systemset.imgaddress
	 * @param imgaddress  the value for systemset.imgaddress
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setImgaddress(String imgaddress) {
		this.imgaddress = imgaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column systemset.vedioaddress
	 * @return  the value of systemset.vedioaddress
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getVedioaddress() {
		return vedioaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column systemset.vedioaddress
	 * @param vedioaddress  the value for systemset.vedioaddress
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setVedioaddress(String vedioaddress) {
		this.vedioaddress = vedioaddress;
	}
}