package com.livinglibrary.po;

import java.util.Date;

public class Userpost {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userpost.tid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private String tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userpost.stuid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private String stuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userpost.postid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private Long postid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userpost.replynum
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private Long replynum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userpost.topic
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private String topic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userpost.replydate
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private Date replydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userpost.clicknum
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private Long clicknum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userpost.status
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userpost.text
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	private String text;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userpost.tid
	 * @return  the value of userpost.tid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public String getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userpost.tid
	 * @param tid  the value for userpost.tid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setTid(String tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userpost.stuid
	 * @return  the value of userpost.stuid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public String getStuid() {
		return stuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userpost.stuid
	 * @param stuid  the value for userpost.stuid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setStuid(String stuid) {
		this.stuid = stuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userpost.postid
	 * @return  the value of userpost.postid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Long getPostid() {
		return postid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userpost.postid
	 * @param postid  the value for userpost.postid
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setPostid(Long postid) {
		this.postid = postid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userpost.replynum
	 * @return  the value of userpost.replynum
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Long getReplynum() {
		return replynum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userpost.replynum
	 * @param replynum  the value for userpost.replynum
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setReplynum(Long replynum) {
		this.replynum = replynum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userpost.topic
	 * @return  the value of userpost.topic
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public String getTopic() {
		return topic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userpost.topic
	 * @param topic  the value for userpost.topic
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setTopic(String topic) {
		this.topic = topic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userpost.replydate
	 * @return  the value of userpost.replydate
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Date getReplydate() {
		return replydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userpost.replydate
	 * @param replydate  the value for userpost.replydate
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setReplydate(Date replydate) {
		this.replydate = replydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userpost.clicknum
	 * @return  the value of userpost.clicknum
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Long getClicknum() {
		return clicknum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userpost.clicknum
	 * @param clicknum  the value for userpost.clicknum
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setClicknum(Long clicknum) {
		this.clicknum = clicknum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userpost.status
	 * @return  the value of userpost.status
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userpost.status
	 * @param status  the value for userpost.status
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userpost.text
	 * @return  the value of userpost.text
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public String getText() {
		return text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userpost.text
	 * @param text  the value for userpost.text
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setText(String text) {
		this.text = text;
	}
}