package com.livinglibrary.po;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.stuid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String stuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.sex
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Boolean sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.college
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String college;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.type
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.state
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.stuid
	 * @return  the value of user.stuid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getStuid() {
		return stuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.stuid
	 * @param stuid  the value for user.stuid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setStuid(String stuid) {
		this.stuid = stuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.sex
	 * @return  the value of user.sex
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Boolean getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.sex
	 * @param sex  the value for user.sex
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.college
	 * @return  the value of user.college
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getCollege() {
		return college;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.college
	 * @param college  the value for user.college
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setCollege(String college) {
		this.college = college;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.type
	 * @return  the value of user.type
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.type
	 * @param type  the value for user.type
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.state
	 * @return  the value of user.state
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.state
	 * @param state  the value for user.state
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setState(Integer state) {
		this.state = state;
	}
}