package com.livinglibrary.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserpostExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public UserpostExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTidIsNull() {
			addCriterion("tid is null");
			return (Criteria) this;
		}

		public Criteria andTidIsNotNull() {
			addCriterion("tid is not null");
			return (Criteria) this;
		}

		public Criteria andTidEqualTo(String value) {
			addCriterion("tid =", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidNotEqualTo(String value) {
			addCriterion("tid <>", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidGreaterThan(String value) {
			addCriterion("tid >", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidGreaterThanOrEqualTo(String value) {
			addCriterion("tid >=", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidLessThan(String value) {
			addCriterion("tid <", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidLessThanOrEqualTo(String value) {
			addCriterion("tid <=", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidLike(String value) {
			addCriterion("tid like", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidNotLike(String value) {
			addCriterion("tid not like", value, "tid");
			return (Criteria) this;
		}

		public Criteria andTidIn(List<String> values) {
			addCriterion("tid in", values, "tid");
			return (Criteria) this;
		}

		public Criteria andTidNotIn(List<String> values) {
			addCriterion("tid not in", values, "tid");
			return (Criteria) this;
		}

		public Criteria andTidBetween(String value1, String value2) {
			addCriterion("tid between", value1, value2, "tid");
			return (Criteria) this;
		}

		public Criteria andTidNotBetween(String value1, String value2) {
			addCriterion("tid not between", value1, value2, "tid");
			return (Criteria) this;
		}

		public Criteria andStuidIsNull() {
			addCriterion("stuid is null");
			return (Criteria) this;
		}

		public Criteria andStuidIsNotNull() {
			addCriterion("stuid is not null");
			return (Criteria) this;
		}

		public Criteria andStuidEqualTo(String value) {
			addCriterion("stuid =", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidNotEqualTo(String value) {
			addCriterion("stuid <>", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidGreaterThan(String value) {
			addCriterion("stuid >", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidGreaterThanOrEqualTo(String value) {
			addCriterion("stuid >=", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidLessThan(String value) {
			addCriterion("stuid <", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidLessThanOrEqualTo(String value) {
			addCriterion("stuid <=", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidLike(String value) {
			addCriterion("stuid like", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidNotLike(String value) {
			addCriterion("stuid not like", value, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidIn(List<String> values) {
			addCriterion("stuid in", values, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidNotIn(List<String> values) {
			addCriterion("stuid not in", values, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidBetween(String value1, String value2) {
			addCriterion("stuid between", value1, value2, "stuid");
			return (Criteria) this;
		}

		public Criteria andStuidNotBetween(String value1, String value2) {
			addCriterion("stuid not between", value1, value2, "stuid");
			return (Criteria) this;
		}

		public Criteria andPostidIsNull() {
			addCriterion("postid is null");
			return (Criteria) this;
		}

		public Criteria andPostidIsNotNull() {
			addCriterion("postid is not null");
			return (Criteria) this;
		}

		public Criteria andPostidEqualTo(Long value) {
			addCriterion("postid =", value, "postid");
			return (Criteria) this;
		}

		public Criteria andPostidNotEqualTo(Long value) {
			addCriterion("postid <>", value, "postid");
			return (Criteria) this;
		}

		public Criteria andPostidGreaterThan(Long value) {
			addCriterion("postid >", value, "postid");
			return (Criteria) this;
		}

		public Criteria andPostidGreaterThanOrEqualTo(Long value) {
			addCriterion("postid >=", value, "postid");
			return (Criteria) this;
		}

		public Criteria andPostidLessThan(Long value) {
			addCriterion("postid <", value, "postid");
			return (Criteria) this;
		}

		public Criteria andPostidLessThanOrEqualTo(Long value) {
			addCriterion("postid <=", value, "postid");
			return (Criteria) this;
		}

		public Criteria andPostidIn(List<Long> values) {
			addCriterion("postid in", values, "postid");
			return (Criteria) this;
		}

		public Criteria andPostidNotIn(List<Long> values) {
			addCriterion("postid not in", values, "postid");
			return (Criteria) this;
		}

		public Criteria andPostidBetween(Long value1, Long value2) {
			addCriterion("postid between", value1, value2, "postid");
			return (Criteria) this;
		}

		public Criteria andPostidNotBetween(Long value1, Long value2) {
			addCriterion("postid not between", value1, value2, "postid");
			return (Criteria) this;
		}

		public Criteria andReplynumIsNull() {
			addCriterion("replynum is null");
			return (Criteria) this;
		}

		public Criteria andReplynumIsNotNull() {
			addCriterion("replynum is not null");
			return (Criteria) this;
		}

		public Criteria andReplynumEqualTo(Long value) {
			addCriterion("replynum =", value, "replynum");
			return (Criteria) this;
		}

		public Criteria andReplynumNotEqualTo(Long value) {
			addCriterion("replynum <>", value, "replynum");
			return (Criteria) this;
		}

		public Criteria andReplynumGreaterThan(Long value) {
			addCriterion("replynum >", value, "replynum");
			return (Criteria) this;
		}

		public Criteria andReplynumGreaterThanOrEqualTo(Long value) {
			addCriterion("replynum >=", value, "replynum");
			return (Criteria) this;
		}

		public Criteria andReplynumLessThan(Long value) {
			addCriterion("replynum <", value, "replynum");
			return (Criteria) this;
		}

		public Criteria andReplynumLessThanOrEqualTo(Long value) {
			addCriterion("replynum <=", value, "replynum");
			return (Criteria) this;
		}

		public Criteria andReplynumIn(List<Long> values) {
			addCriterion("replynum in", values, "replynum");
			return (Criteria) this;
		}

		public Criteria andReplynumNotIn(List<Long> values) {
			addCriterion("replynum not in", values, "replynum");
			return (Criteria) this;
		}

		public Criteria andReplynumBetween(Long value1, Long value2) {
			addCriterion("replynum between", value1, value2, "replynum");
			return (Criteria) this;
		}

		public Criteria andReplynumNotBetween(Long value1, Long value2) {
			addCriterion("replynum not between", value1, value2, "replynum");
			return (Criteria) this;
		}

		public Criteria andTopicIsNull() {
			addCriterion("topic is null");
			return (Criteria) this;
		}

		public Criteria andTopicIsNotNull() {
			addCriterion("topic is not null");
			return (Criteria) this;
		}

		public Criteria andTopicEqualTo(String value) {
			addCriterion("topic =", value, "topic");
			return (Criteria) this;
		}

		public Criteria andTopicNotEqualTo(String value) {
			addCriterion("topic <>", value, "topic");
			return (Criteria) this;
		}

		public Criteria andTopicGreaterThan(String value) {
			addCriterion("topic >", value, "topic");
			return (Criteria) this;
		}

		public Criteria andTopicGreaterThanOrEqualTo(String value) {
			addCriterion("topic >=", value, "topic");
			return (Criteria) this;
		}

		public Criteria andTopicLessThan(String value) {
			addCriterion("topic <", value, "topic");
			return (Criteria) this;
		}

		public Criteria andTopicLessThanOrEqualTo(String value) {
			addCriterion("topic <=", value, "topic");
			return (Criteria) this;
		}

		public Criteria andTopicLike(String value) {
			addCriterion("topic like", value, "topic");
			return (Criteria) this;
		}

		public Criteria andTopicNotLike(String value) {
			addCriterion("topic not like", value, "topic");
			return (Criteria) this;
		}

		public Criteria andTopicIn(List<String> values) {
			addCriterion("topic in", values, "topic");
			return (Criteria) this;
		}

		public Criteria andTopicNotIn(List<String> values) {
			addCriterion("topic not in", values, "topic");
			return (Criteria) this;
		}

		public Criteria andTopicBetween(String value1, String value2) {
			addCriterion("topic between", value1, value2, "topic");
			return (Criteria) this;
		}

		public Criteria andTopicNotBetween(String value1, String value2) {
			addCriterion("topic not between", value1, value2, "topic");
			return (Criteria) this;
		}

		public Criteria andReplydateIsNull() {
			addCriterion("replydate is null");
			return (Criteria) this;
		}

		public Criteria andReplydateIsNotNull() {
			addCriterion("replydate is not null");
			return (Criteria) this;
		}

		public Criteria andReplydateEqualTo(Date value) {
			addCriterion("replydate =", value, "replydate");
			return (Criteria) this;
		}

		public Criteria andReplydateNotEqualTo(Date value) {
			addCriterion("replydate <>", value, "replydate");
			return (Criteria) this;
		}

		public Criteria andReplydateGreaterThan(Date value) {
			addCriterion("replydate >", value, "replydate");
			return (Criteria) this;
		}

		public Criteria andReplydateGreaterThanOrEqualTo(Date value) {
			addCriterion("replydate >=", value, "replydate");
			return (Criteria) this;
		}

		public Criteria andReplydateLessThan(Date value) {
			addCriterion("replydate <", value, "replydate");
			return (Criteria) this;
		}

		public Criteria andReplydateLessThanOrEqualTo(Date value) {
			addCriterion("replydate <=", value, "replydate");
			return (Criteria) this;
		}

		public Criteria andReplydateIn(List<Date> values) {
			addCriterion("replydate in", values, "replydate");
			return (Criteria) this;
		}

		public Criteria andReplydateNotIn(List<Date> values) {
			addCriterion("replydate not in", values, "replydate");
			return (Criteria) this;
		}

		public Criteria andReplydateBetween(Date value1, Date value2) {
			addCriterion("replydate between", value1, value2, "replydate");
			return (Criteria) this;
		}

		public Criteria andReplydateNotBetween(Date value1, Date value2) {
			addCriterion("replydate not between", value1, value2, "replydate");
			return (Criteria) this;
		}

		public Criteria andClicknumIsNull() {
			addCriterion("clicknum is null");
			return (Criteria) this;
		}

		public Criteria andClicknumIsNotNull() {
			addCriterion("clicknum is not null");
			return (Criteria) this;
		}

		public Criteria andClicknumEqualTo(Long value) {
			addCriterion("clicknum =", value, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumNotEqualTo(Long value) {
			addCriterion("clicknum <>", value, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumGreaterThan(Long value) {
			addCriterion("clicknum >", value, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumGreaterThanOrEqualTo(Long value) {
			addCriterion("clicknum >=", value, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumLessThan(Long value) {
			addCriterion("clicknum <", value, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumLessThanOrEqualTo(Long value) {
			addCriterion("clicknum <=", value, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumIn(List<Long> values) {
			addCriterion("clicknum in", values, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumNotIn(List<Long> values) {
			addCriterion("clicknum not in", values, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumBetween(Long value1, Long value2) {
			addCriterion("clicknum between", value1, value2, "clicknum");
			return (Criteria) this;
		}

		public Criteria andClicknumNotBetween(Long value1, Long value2) {
			addCriterion("clicknum not between", value1, value2, "clicknum");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table userpost
	 * @mbg.generated  Sat Jan 12 10:57:32 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userpost
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 11 19:49:21 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}