package com.livinglibrary.po;

public class UserRoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.uid
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.roleid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer roleid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.uid
	 * @return  the value of user_role.uid
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.uid
	 * @param uid  the value for user_role.uid
	 * @mbg.generated  Thu May 16 08:51:20 CST 2019
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.roleid
	 * @return  the value of user_role.roleid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.roleid
	 * @param roleid  the value for user_role.roleid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}
}