package com.livinglibrary.po;

import java.util.Date;

public class UserRole extends UserRoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.addtime
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Date addtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.addtime
	 * @return  the value of user_role.addtime
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.addtime
	 * @param addtime  the value for user_role.addtime
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}
}