package com.livinglibrary.po;

import java.util.Date;

public class Vediotype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vediotype.typeid
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vediotype.typename
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    private String typename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vediotype.createtime
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vediotype.description
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vediotype.typeid
     *
     * @return the value of vediotype.typeid
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vediotype.typeid
     *
     * @param typeid the value for vediotype.typeid
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vediotype.typename
     *
     * @return the value of vediotype.typename
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vediotype.typename
     *
     * @param typename the value for vediotype.typename
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    public void setTypename(String typename) {
        this.typename = typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vediotype.createtime
     *
     * @return the value of vediotype.createtime
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vediotype.createtime
     *
     * @param createtime the value for vediotype.createtime
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vediotype.description
     *
     * @return the value of vediotype.description
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vediotype.description
     *
     * @param description the value for vediotype.description
     *
     * @mbg.generated Thu May 16 08:51:21 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }
}