package com.livinglibrary.po;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

public class Vedio {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vedio.id
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vedio.url
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vedio.title
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vedio.img
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vedio.typeid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer typeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vedio.description
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vedio.createtime
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	@JSONField(format = "yyyy-MM-dd HH:mm:ss")
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vedio.playvolume
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	private Integer playvolume;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vedio.id
	 * @return  the value of vedio.id
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vedio.id
	 * @param id  the value for vedio.id
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vedio.url
	 * @return  the value of vedio.url
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vedio.url
	 * @param url  the value for vedio.url
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vedio.title
	 * @return  the value of vedio.title
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vedio.title
	 * @param title  the value for vedio.title
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vedio.img
	 * @return  the value of vedio.img
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vedio.img
	 * @param img  the value for vedio.img
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setImg(String img) {
		this.img = img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vedio.typeid
	 * @return  the value of vedio.typeid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getTypeid() {
		return typeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vedio.typeid
	 * @param typeid  the value for vedio.typeid
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setTypeid(Integer typeid) {
		this.typeid = typeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vedio.description
	 * @return  the value of vedio.description
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vedio.description
	 * @param description  the value for vedio.description
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vedio.createtime
	 * @return  the value of vedio.createtime
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vedio.createtime
	 * @param createtime  the value for vedio.createtime
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vedio.playvolume
	 * @return  the value of vedio.playvolume
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public Integer getPlayvolume() {
		return playvolume;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vedio.playvolume
	 * @param playvolume  the value for vedio.playvolume
	 * @mbg.generated  Thu May 16 08:51:21 CST 2019
	 */
	public void setPlayvolume(Integer playvolume) {
		this.playvolume = playvolume;
	}
}